### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/kafka/clients/producer/KafkaProducer

### ISSUE THREAD

**Issue by qq12157138** [jxttian/logging-appender#1]
我将工程打包成jar，然后依赖到其他工程中，启动就报这个错。我的是logback-spring.xml

> java.lang.NoClassDefFoundError: org/apache/kafka/clients/producer/KafkaProducer
	at net.myscloud.plugin.logging.logback.build.KafkaBuildStrategy.build(KafkaBuildStrategy.java:31)
	at net.myscloud.plugin.logging.logback.LogbackAppender.start(LogbackAppender.java:54)

**Comment by qq12157138** [comment]
> <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-clients</artifactId>
            <version>0.10.2.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.myscloud.plugin</groupId>
            <artifactId>logging-appender</artifactId>
            <version>1.1</version>
        </dependency>

**Comment by qq12157138** [comment]
是不是不支持springboot 啊

**Comment by jxttian** [comment]
支持的   kafka-clients 的 scope是provided 所以你需要在自己的pom文件中添加kafka-clients依赖

**Comment by jxttian** [comment]
支持springboot的     这边我把kafka client的依赖scope声明为provided 所以你需要在自己的pom中添加kafka-clients依赖

**Comment by qq12157138** [comment]
@jxttian 你看我pom我都依赖了kafka-clients 然而启动还是报错。

**Comment by jxttian** [comment]
@qq12157138 把 <scope>provided</scope>去掉

**Comment by qq12157138** [comment]
@jxttian 

> 
java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.spi.Interpreter@163:17 - no applicable action for [source], current ElementPath  is [[configuration][appender][source]]
ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - Could not find an appender named [Console]. Did you define it below instead of above in the configuration file?
ERROR in ch.qos.logback.core.joran.action.AppenderRefAction - See http://logback.qos.ch/codes.html#appender_order for more details.

**Comment by qq12157138** [comment]
@jxttian 谢谢楼主，成功了。那个<source>是干嘛的，加上报错

**Comment by qq12157138** [comment]
@jxttian 谢谢楼主，成功了，那个source是干嘛的 加上报错

**Comment by jxttian** [comment]
不客气, source以前是用来区分日志来源的 ,在springboot下报错可以不加

**Comment by qq12157138** [comment]
@jxttian 其实在springboot下，按道理addresses中的地址应该在配置文件中配置才对。要不然配置中心也没办法管理了

**Comment by jxttian** [comment]
@qq12157138 恩  因为之前做这个的时候并没有使用springboot,后面有时间的话会考虑加一下

**Comment by qq12157138** [comment]
@jxttian 还有个问题，你这个日志格式在哪调整啊，你输出这几个字段太少。我想加几个

**Comment by jxttian** [comment]
@qq12157138 在JSONEvent 中
